#!/usr/bin/env python3
"""
MIA Academy pricing catalog extractor.

Single source of truth = the live product pages in this repo. Prices drift when
edited by hand across many files, so this regenerates a canonical PRICING.md by
reading each product page's <meta name="description"> (authoritative selling
price) plus the two index pages (academy/ and academy/sme/) for cross-check.

Usage:
    python3 tools/pricing-catalog.py            # writes PRICING.md
    python3 tools/pricing-catalog.py --check     # prints, exits 1 on mismatch

Re-run after any pricing edit. Keep PRICING.md committed so skills and the vault
read one file instead of grepping 20 pages.
"""
import re, os, sys, glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# product page dir -> display name (order = catalog order)
PAGES = [
    ("academy/pro-bootcamp",        "Product & Growth Marketing with AI Bootcamp"),
    ("academy/dime",                "DIME (Digital Income Made Easy)"),
    ("academy/dime-masterclass",    "DIME Masterclass"),
    ("academy/dime-dfy",            "DIME Done-For-You"),
    ("academy/pmm-course",          "Complete Product Marketing Course"),
    ("academy/tech-sales",          "Complete Tech Sales Course"),
    ("academy/growth-handbook",     "Complete Growth Marketing Handbook"),
    ("academy/digital-marketing",   "Complete Digital Marketing Guide"),
    ("academy/ai-prompts",          "AI Prompt Frameworks & Templates"),
    ("academy/templates",           "Product Marketing Templates & Resources Library"),
    ("academy/sme/meta-ads",        "Meta Ads Simplified (Workshop)"),
    ("academy/sme/tiktok-ads",      "TikTok Ads Simplified (Workshop)"),
    ("academy/sme/page-optimization","Business Page Optimization Simplified (Workshop)"),
    ("academy/sme/automation",      "Social Automation Simplified (Workshop)"),
    ("academy/sme/safety-net",      "Meta Account Recovery Workshop"),
    ("academy/sme/target-buyer",    "Target Buyer Sales Masterclass"),
    ("academy/sme/bundle",          "Online Marketing Mentorship (Bundle)"),
    ("academy/sme/targeting-setup", "The Profitable Ads Targeting Setup"),
    ("academy/sme/consulting",      "Online Marketing Consulting"),
    ("academy/sme/team-training",   "SME Team Training"),
]

# NGN amount: ₦ then 1-3 digits, optional ,000 groups, optional /mo|/yr suffix.
NGN = r'₦\d{1,3}(?:,\d{3})*(?:/(?:mo|yr|year|month))?'
PRICE_RE = re.compile(r'(?:Pro\s*' + NGN + r'\s*·\s*Core\s*' + NGN + r'|From\s*' + NGN + r'|' + NGN + r')')

def meta_desc(html):
    m = re.search(r'<meta name="description" content="([^"]*)"', html)
    return m.group(1) if m else ""

def extract(path):
    """Prefer the price the page's meta description ends with (authoritative
    selling price). Fall back to the first 'From ₦…' or ₦ price in the page
    body for pages whose meta description omits the price (e.g. team training)."""
    fp = os.path.join(ROOT, path, "index.html")
    if not os.path.exists(fp):
        return None, "MISSING PAGE"
    html = open(fp, encoding="utf-8").read()
    desc = meta_desc(html)
    hits = PRICE_RE.findall(desc)
    if hits:
        return hits[-1].strip(), desc
    body = re.sub(r'<script.*?</script>|<style.*?</style>', ' ', html, flags=re.S)
    body = re.sub(r'<[^>]+>', ' ', body)
    fm = re.search(r'From\s*' + NGN, body)
    if fm:
        return fm.group(0).strip(), desc
    # Fallback: read the price shown on the index card that links to this page.
    idx_price = index_card_price(path)
    if idx_price:
        return idx_price, desc
    bm = PRICE_RE.search(body)
    return (bm.group(0).strip() if bm else None), desc

_INDEX_CACHE = {}
def index_card_price(path):
    """Find the price displayed near the index-page card linking to /path/."""
    for idx in ("academy/index.html", "academy/sme/index.html"):
        html = _INDEX_CACHE.get(idx)
        if html is None:
            fp = os.path.join(ROOT, idx)
            html = open(fp, encoding="utf-8").read() if os.path.exists(fp) else ""
            _INDEX_CACHE[idx] = html
        leaf = path.rstrip("/").split("/")[-1]
        m = re.search(re.escape(leaf) + r'/["\']', html)
        if not m:
            continue
        window = html[max(0, m.start() - 1200): m.start() + 400]
        window = re.sub(r'<[^>]+>', ' ', window)
        hits = re.findall(r'From\s*' + NGN + r'|' + NGN, window)
        if hits:
            return hits[-1].strip()  # nearest price before the link
    return None

def main():
    rows = []
    for path, name in PAGES:
        price, _ = extract(path)
        rows.append((name, price or "—", path))

    out = ["# MIA Academy — Canonical Pricing Catalog", ""]
    out.append("Auto-generated by `tools/pricing-catalog.py` from each product page's")
    out.append("meta description (the authoritative selling price). Re-run after any")
    out.append("price edit. Do not hand-edit this file.")
    out.append("")
    out.append("| Product | Price | Page |")
    out.append("|---|---|---|")
    for name, price, path in rows:
        out.append(f"| {name} | {price} | /{path}/ |")
    out.append("")
    out.append("Notes:")
    out.append("- DIME founding price is ₦45,000; webinar attendees get a discounted ₦35,000.")
    out.append("- Consulting: ₦250,000/mo (1-mo), ₦225,000/mo (3-mo = ₦675,000), ₦200,000/mo (6-mo = ₦1,200,000).")
    out.append("- Bootcamp: Pro ₦75,000 / Core ₦45,000 (upgrade = ₦30,000 difference).")
    out.append("- $ figures on career pages are salary/market context, NOT product prices.")

    text = "\n".join(out) + "\n"
    if "--check" in sys.argv:
        print(text)
        if any(p in ("—", "MISSING PAGE") for _, p, _ in rows):
            sys.exit(1)
        return
    open(os.path.join(ROOT, "PRICING.md"), "w", encoding="utf-8").write(text)
    print(f"Wrote PRICING.md with {len(rows)} products.")

if __name__ == "__main__":
    main()
